Question 1 :
    pour f1() : RuntimeException n'est pas obligé d'être indiqué
    donc pas de pb.
    pour f2() : Il faut indiquer pour une IOExcpetion throw
    IOExcpetion dans la signature de la fonction donc erreur lors
    de la compilation

- Exc3

    finally f4
    finally f3
    <Inturreption programme>

- Exc31

    finally f4
    Exc31 (capture par f3())
    finally f3
    suite f3

- Exc311

    idem que Exc31 sauf affichage de la classe

- Exc32

    Exc32
    finally f4
    suite f4
    finally f3
    suite f3

- Exc321

    Exc321
    ensuite comme le cas Exc32


Question 3 :
    TAILLE_MAX = 0 : Le main pense que la pile est pleine
                     sortie du main

    TAILLE_MAX = 1 : sortie de empiler
                     le main pense que la pile est pleine
                     Sortie du main

    TAILLE_MAX = 2 : sortie de empiler
                     sortie de empiler

                     sortie de sommet
                     4
                     sortie de dépiler
                     sortie de sommet
                     2
                     sortie de dépiler

                     le depilerTout est passé par la
                     sortie du depilerTout

                     le main pense que la pile est vide
                     sortie du main

Question 4 :
    while (!estVide() || nb!=0) {
        try {
            system.out.println(sommet());
            depiler();
        }
        catch(PVE e) {} // ne devrait jamais arriver
    }
